# -*- coding: utf-8 -*-
"""GP_survey_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9YZ5t_ltaO41C1dOGfb7H_atizXa0Q0
"""

# Combining location and patient experience
from foundry.transforms import Dataset

import pandas as pd
import numpy as np
gp_survey_data = Dataset.get("all_responses_ons_health_survey_cut").read_table(format="pandas")

gp_survey_data.rename(columns={'untitled_column': 'Percentage_response'}, inplace=True)
gp_survey_data.head()
result = gp_survey_data.dtypes

print("Output:")
print(result)


gp_survey_data["Percentage_response"] = pd.to_numeric(gp_survey_data["Percentage_response"])

# Print unique questions
count = gp_survey_data['Question'].nunique()
count
# Print unique demo cateogory
# Print unique Demo breakdown

# Overall, how would you describe your experience in your GP practice
# Over the last 12 months, how do you think the service provided by your GP practice has changed?
overall_experience = gp_survey_data[gp_survey_data['Question'] == 'Overall, how would you describe your experience of your GP practice?']
overall_experience

overall_experience.to_csv('overall_experience.csv', index=False)

# Commented out IPython magic to ensure Python compatibility.
# Plotting for three category answers: Overall, how would you describe your experience in your GP practice

# %pip install --upgrade plotly
import plotly.express as px

# Commented out IPython magic to ensure Python compatibility.
# Assuming overall_experience is your DataFrame
#  %pip install matplotlib


import matplotlib.pyplot as plt

x_labels = overall_experience['Response_option']
y_values = overall_experience['Percentage_response']

# Define NHS blue and greys
nhs_blue = '#0072CE'
greys = ['#A7A9AC', '#4C4F53', '#6F7B82']

# Create a colors list where first three bars are blue, remaining are greys
colors = [nhs_blue]*3 + greys[:max(0, len(x_labels)-3)]

fig, ax = plt.subplots(figsize=(10, 6))

bars = ax.bar(x_labels, y_values, color=colors[:len(x_labels)], edgecolor='none')

# Add percentage labels on top of bars
ax.bar_label(bars, fmt='%.1f%%', padding=5, fontsize=10, fontweight='bold', color='#0B3E6F')

# Title and labels with NHS colours
ax.set_title('Overall, how would you describe your experience in your GP practice', fontsize=16, fontweight='bold', color='#004B87')
ax.set_ylabel('Percentage Response (%)', fontsize=14, color='#004B87')


# Rotate x labels for clarity
plt.xticks(rotation=45, ha='right', fontsize=12, color='#333333')

# Add subtle horizontal grid lines only
ax.yaxis.grid(True, linestyle='--', alpha=0.5)
ax.xaxis.grid(False)

# Remove top and right borders
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

#1. What was your main reason for trying to contact your GP practice?
#2. Thinking of the last time you tried to contact your GP practice, did you manage to make contact with them?
#nThis could be in person, on the phone or online.
#%pip install seaborn

import seaborn as sns
gp_survey_data['Question'] = gp_survey_data['Question'].str.strip()
print(gp_survey_data)

#gp_survey_data['Question'] = gp_survey_data['Question'].str.strip()
#questions_of_interest = [
    #'What was your main reason for trying to contact your GP practice?',
    #'Thinking of the last time you tried to contact your GP practice, did you manage to make contact with them? This could be in person, on the phone or online.'

questions_of_interest = [
    'What was your main reason for trying to contact your GP practice?',
    'Thinking of the last time you tried to contact your GP practice, did you manage to make contact with them?'
]

gp_contact = gp_survey_data[gp_survey_data['Question'].isin(questions_of_interest)]


gp_contact.head()

x_labels = gp_contact['Response_option']
y_values = gp_contact['Percentage_response']

# Use NHS blue for all bars
nhs_blue = '#0072CE'
colors = [nhs_blue] * len(x_labels)

fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(x_labels, y_values, color=colors, edgecolor='none')

# Add percentage labels on top of bars
ax.bar_label(bars, fmt='%.1f%%', padding=5, fontsize=10, fontweight='bold', color='#0B3E6F')

# Title and labels with NHS colours
ax.set_title('Main reason for recently contacting GP?', fontsize=16, fontweight='bold', color='#004B87')
ax.set_ylabel('Percentage Response (%)', fontsize=14, color='#004B87')

# Rotate x labels for clarity
plt.xticks(rotation=45, ha='right', fontsize=12, color='#333333')

# Add subtle horizontal grid lines only
ax.yaxis.grid(True, linestyle='--', alpha=0.5)
ax.xaxis.grid(False)

# Remove top and right borders
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()